### ISSUE TITLE
Is there any plan about llm?

### ISSUE THREAD

**Issue by dsp6414** [DunnBC22/Data_Engineering_Projects#1]
I greatly appreciate your open-source repository, which has been very helpful to me. May I ask if you will have any open-source projects related to large language models in the future?

**Comment by DunnBC22** [comment]
Hi @dsp6414 , As much as I want to do some projects with large language models, I just do not have the computing resources to do so.

**Comment by dsp6414** [comment]
The same to you, our laboratory only has one dual card A100 GPU server.☺️

**Comment by dsp6414** [comment]
🌺
